#!/bin/bash

export EDITOR="nvim"


export PATH=$PATH:~/.local/bin/:~/node_modules/.bin
export NODE_USE_ENV_PROXY=1

# Load SEL-specific environment variables if .sel file exists
if [ -f ~/.sel ]; then
    source ~/.sel
fi
